#cloud-config
chpasswd:
  expire: False
ssh_pwauth: True

users:
  - default
  - name: gabriel # login name
    gecos: Gabriel # Contacts of user
    primary_group: users
    lock_passwd: false # Disable password login (default is true)
    passwd: '$6$rounds=4096$ED.genr8O/IZRcad$WcIGeY7ebeWKa4SEkJIrq/AHG.8wRBue1vsVi9FNeqPK7HVFmAlXI/TeAO2XZ.nVTwem4gCHDXFGvWfukP9MP/' # hashed password for user: senha
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICzK/2w/gtx0UMJZsyeO1Kt16mHPs+GvGQsEa1+1M1T2 gabrielnovaisgs@gmail.com

network:
  version: 2
  ethernets:
    enp1s0:
      dhcp4: true # Activate DHCP to have an ip address


