all:
  vars:
    ansible_user: gabriel
    ansible_ssh_private_key_file: ~/.ssh/cloud-init-local
    ansible_ssh_common_args: '-o IdentitiesOnly=yes'
  children:
    k8s_masters:
      hosts:
        k8s_master:
          ansible_host: 192.168.124.2
    
    k8s_workers:
      hosts:
        k8s_worker_1:
          ansible_host: 192.168.124.3
        k8s_worker_2:
          ansible_host: 192.168.124.4