- name: Play 1 - Preparar os nodes
  hosts: all
  tasks:
    - name: Disable swap
      become: true
      ansible.posix.mount:
        name: swap
        fstype: swap
        state: absent # tells Ansible to remove the entry from /etc/fstab and unmount the corresponding swap space.

    - name: Load necessary kernel
      become: true
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: "0644"
        create: true

    - name: Load modules
      become: true
      community.general.modprobe:
        name: "{{ item }}" # 'item' é uma variável especial que o loop preenche
        state: present # garante que o module esteja carregado
      loop:
        - overlay
        - br_netfilter

    - name: Load the system parameters
      become: true
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 1
        state: present # Garante que a configuração exista
        sysctl_file: /etc/sysctl.d/k8s.conf # Torna persistente
        reload: true # Aplica imediatamente
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward
