- name: Play 1 - Preparar os nodes
  hosts: all
  tasks:
    - name: Disable swap
      become: true
      ansible.posix.mount:
        name: swap
        fstype: swap
        state: absent # tells Ansible to remove the entry from /etc/fstab and unmount the corresponding swap space.

    - name: Load necessary kernel
      become: true
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: "0644"
        create: true

    - name: Load modules
      become: true
      community.general.modprobe:
        name: "{{ item }}" # 'item' é uma variável especial que o loop preenche
        state: present # garante que o module esteja carregado
      loop:
        - overlay
        - br_netfilter

    - name: Load the system parameters
      become: true
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 1
        state: present # Garante que a configuração exista
        sysctl_file: /etc/sysctl.d/k8s.conf # Torna persistente
        reload: true # Aplica imediatamente
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward

    - name: Install basic dependecies
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
          - lsb-release

    - name: Download Kubernetes Release.key
      become: true
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: "0644"

    - name: Convert Release.key to GPG keyring
      become: true
      ansible.builtin.command:
        cmd: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key"
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add kuibernets apt repository
      become: true
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        block: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
        state: present
        owner: root
        group: root
        mode: "0644"
        create: true

    - name: Install kubelet and kubadm
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - kubelet
          - kubeadm
          - kubectl

    - name: Hold packages
      become: true
      ansible.builtin.dpkg_selections: # evita que os pacotes sumam no futuro caso ocorra algum upgrade aleatório
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Download container.d Release.key
      become: true
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/containerd-release.key
        mode: "0644"

    - name: Convert containerd.key to GPG keyring
      become: true
      ansible.builtin.command:
        cmd: "gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /tmp/containerd-release.key"
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add containerd apt repository
      become: true
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list.d/docker.list
        block: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
        owner: root
        group: root
        mode: "0644"
        create: true

    - name: Install containerd
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - containerd.io

    - name: Create containerd config
      become: true
      ansible.builtin.command:
        cmd: "containerd config default | tee /etc/containerd/config.toml"
      args:
        creates: /etc/containerd/config.toml

    - name: Enable the CRI plugin in containerd
      become: true
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        #  habilita o plugin do K8s
        regexp: 'disabled_plugins = \["cri"\]'
        replace: '# disabled_plugins = ["cri"]'

    - name: Config cgroup
      become: true
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: "SystemdCgroup = false"
        replace: "SystemdCgroup = true"

    - name: Restart container.d
      become: true
      ansible.builtin.systemd:
        name: containerd
        enabled: true
        state: restarted

    - name: Enable kubelet
      become: true
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
        state: started

- name: Play 2 - Preparando o node master
  hosts: k8s_master
  tasks:
    - name: Open master ports (tcp)
      become: true
      community.general.ufw: # https://v1-33.docs.kubernetes.io/docs/reference/networking/ports-and-protocols/ and weave port
        state: enabled
        rule: allow
        proto: tcp
        port: "{{ item }}"
      loop:
        - 6443
        - 2379:2380
        - 10250
        - 10259
        - 10257
        - 22
        - 6783

    - name: Open master ports (udp)
      become: true
      community.general.ufw:
        state: enabled
        rule: allow
        proto: udp
        port: 6783:6784

    - name: Init kubeadm
      become: true
      ansible.builtin.command:
        cmd: "kubeadm init --pod-network-cidr=10.10.0.0/16 --apiserver-advertise-address=192.168.124.2"
      args:
        creates: /etc/kubernetes/admin.conf
      async: 600 # 10 minutos
      poll: 5

    - name: Create .kube folder
      become: true
      ansible.builtin.file:
        path: /home/gabriel/.kube
        state: directory
        owner: gabriel
        group: gabriel
        mode: "0700"

    - name: Copy kube config
      become: true
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/gabriel/.kube/config
        owner: gabriel
        group: gabriel
        mode: "0600"
        remote_src: true # diz para ansible que o src é remoto e não local

    - name: Restart kubelet
      become: true
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
        state: restarted

    - name: Wait for API server to be ready
      remote_user: gabriel
      ansible.builtin.command:
        cmd: kubectl get --raw /healthz
      register: api_health
      until: api_health.rc == 0
      retries: 30
      delay: 10
      changed_when: false

    - name: Install CNI (Weave Net)
      remote_user: gabriel
      ansible.builtin.command:
        cmd: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
      changed_when: false

    - name: Get the kubeadm join command
      become: true
      ansible.builtin.command:
        cmd: "kubeadm token create --print-join-command"
      register: join_command_raw
      changed_when: false

    - name: Set join command as a fact
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout }}"

- name: Play 3 - Preparando o node worker
  hosts: k8s_workers
  tasks:
    - name: Open worker ports (tcp) # https://v1-33.docs.kubernetes.io/docs/reference/networking/ports-and-protocols/
      become: true
      community.general.ufw:
        state: enabled
        rule: allow
        proto: tcp
        port: "{{ item }}"
      loop:
        - 10250
        - 20256
        - 30000:32767
        - 22

    - name: Open worker ports (udp)
      become: true
      community.general.ufw:
        state: enabled
        rule: allow
        proto: udp
        port: 30000:32767

    - name: Join node to cluster
      become: true
      ansible.builtin.command:
        cmd: "{{ hostvars['k8s_master']['join_command'] }}" # get variable from the previous host
      changed_when: false
