- name: Play 1 - Preparar os nodes
  hosts: all
  tasks:
    - name: Disable swap
      become: true
      ansible.posix.mount:
        name: swap
        fstype: swap
        state: absent # tells Ansible to remove the entry from /etc/fstab and unmount the corresponding swap space.

    - name: Load necessary kernel
      become: true
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: "0644"
        create: true

    - name: Load modules
      become: true
      community.general.modprobe:
        name: "{{ item }}" # 'item' é uma variável especial que o loop preenche
        state: present # garante que o module esteja carregado
      loop:
        - overlay
        - br_netfilter

    - name: Load the system parameters
      become: true
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 1
        state: present # Garante que a configuração exista
        sysctl_file: /etc/sysctl.d/k8s.conf # Torna persistente
        reload: true # Aplica imediatamente
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward

    - name: Install basic dependecies
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
          - lsb-release

    - name: Download Kubernetes Release.key
      become: true
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: "0644"

    - name: Convert Release.key to GPG keyring
      become: true
      ansible.builtin.command:
        cmd: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key"
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add kuibernets apt repository
      become: true
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        block: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
        state: present
        owner: root
        group: root
        mode: "0644"
        create: true

    - name: Install kubelet and kubadm
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - kubelet
          - kubeadm
          - kubectl

    - name: Hold packages
      become: true
      ansible.builtin.dpkg_selections: # evita que os pacotes sumam no futuro caso ocorra algum upgrade aleatório
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Download container.d Release.key
      become: true
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/containerd-release.key
        mode: "0644"

    - name: Convert containerd.key to GPG keyring
      become: true
      ansible.builtin.command:
        cmd: "gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /tmp/containerd-release.key"
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add containerd apt repository
      become: true
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list.d/docker.list
        block: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
        owner: root
        group: root
        mode: "0644"
        create: true

    - name: Install containerd
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - containerd.io

    #- name: Open firewall ports
    #  community.general.ufw:
    #    state: enabled
    #    rule: allow
    #    port: "{{item}}"
